name: Build mGBA with Python Bindings on Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cffi
        shell: cmd

      - name: Install CMake
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
        shell: powershell

      - name: Update vcpkg
        run: |
          cd C:\vcpkg
          git pull
          C:\vcpkg\bootstrap-vcpkg.bat
        shell: cmd

      - name: Install dependencies
        run: |
          vcpkg install libpng sdl2 zlib libepoxy --triplet x64-windows
        shell: cmd

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. -DBUILD_PYTHON=ON -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake
        shell: cmd

      - name: Generate lib.c for Python binding
        run: |
          cd build
          set BINDIR=D:/a/mgba/mgba/build/Release
          set CPPFLAGS=-IC:/hostedtoolcache/windows/Python/3.11.9/x64/include -IC:/vcpkg/installed/x64-windows/include
          python D:/a/mgba/mgba/src/platform/python/_builder.py > lib.c
          type lib.c
        shell: cmd

      - name: Build mGBA
        run: |
          cd build
          cmake --build . --config Release --target mgba-pylib
        shell: cmd

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mgba-windows-build
          path: build/Release/
